Add environment
arianna-h-h/gist-uploader pull request #1
Opened 2017-09-12 22:18 UTC by arianna-h-h

2017-09-12 22:20 UTC, ghaynes1292 commented on hello.js
> +const http = require('http');
server.js

2017-09-12 22:21 UTC, arianna-h-h commented on hello.js
> +const http = require('http');
done

2017-09-12 22:37 UTC, snmgian requested changes

2017-09-12 22:37 UTC, snmgian commented on package.json
> +    "import": "0.0.6"
why do we need this?

2017-09-12 22:37 UTC, snmgian commented on package.json
> +    "eslint-plugin-import": "^2.7.0",
Shouldn't be included as a dev dependency ?

2017-09-13 11:20 UTC, snmgian approved these changes

2017-09-13 14:39 UTC, merged